parameters:
  mamay.victim: 'https://www.askgamblers.com/'

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Mamay\Bundle\ScrapingBundle\:
    resource: '../../'
    exclude: '../../{DependencyInjection,Resources,Dto}'

  Mamay\Bundle\ScrapingBundle\Controller\DefaultController:
    class: Mamay\Bundle\ScrapingBundle\Controller\DefaultController
    tags: ['controller.service_arguments']
    arguments:
      - '@Mamay\Bundle\ScrapingBundle\Service\Reader'
      - '@Mamay\Bundle\ScrapingBundle\Service\SourceVictim'