index:
    path: /
    controller: App\Controller\DefaultController::index
    methods: [GET]

contacts:
    path: /contacts
    controller: App\Controller\DefaultController::contacts
    methods: [GET]

greeflas_newsletter:
resource: '@GreeflasNewsletterBundle/Resources/config/routes.yaml'