parameters:
  app.file_to_load: '../var/file_storage/subscribers.csv'

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Greeflas\Bundle\NewsletterBundle\:
    resource: '../../*'
    exclude: '../../{DependencyInjection,Resources,Dto}'

  Greeflas\Bundle\NewsletterBundle\Controller\DefaultController:
    tags: ['controller.service_arguments']

  Greeflas\Bundle\NewsletterBundle\Dto\CsvUploader:
    class: Greeflas\Bundle\NewsletterBundle\Dto\CsvUploader
    calls:
      - [setFileToLoad, ['%app.file_to_load%']]