parameters:
  greeflas.storage_file_path: '%kernel.project_dir%/var/file_storage/subscribers.csv'

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Greeflas\Bundle\NewsletterBundle\:
    resource: '../../*'
    exclude: '../../{DependencyInjection,Resources,Dto}'

  Greeflas\Bundle\NewsletterBundle\Controller\DefaultController:
    tags: ['controller.service_arguments']

  Greeflas\Bundle\NewsletterBundle\Repository\CsvFileRepository:
    class: Greeflas\Bundle\NewsletterBundle\Repository\CsvFileRepository
    arguments:
      - '%greeflas.storage_file_path%'